name: Build Flask App to EXE

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment to build the EXE
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your app's dependencies
        pip install pyinstaller  # Install PyInstaller

    - name: Build .exe using PyInstaller
      run: |
        pyinstaller website.spec  # Build your app with PyInstaller (use the .spec file)

    - name: Upload the .exe as a GitHub release asset
      uses: softprops/action-gh-release@v1  # GitHub Action to upload files to a release
      with:
        files: D:/a/cinema_program/cinema_program/dist/website.exe  # Path to your generated .exe file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        
